// Mocks generated by Mockito 5.1.0 from annotations
// in mc_crud_test/test/features/crud/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mc_crud_test/core/error_and_success/succeses.dart' as _i5;
import 'package:mc_crud_test/features/crud/data/data_sources/user_local_data_source.dart'
    as _i2;
import 'package:mc_crud_test/features/crud/data/models/user_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i2.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int>? createUser(_i4.UserModel? user) =>
      (super.noSuchMethod(Invocation.method(#createUser, [user]))
          as _i3.Future<int>?);
  @override
  _i3.Future<_i5.Success>? deleteUser(_i4.UserModel? user) =>
      (super.noSuchMethod(Invocation.method(#deleteUser, [user]))
          as _i3.Future<_i5.Success>?);
  @override
  _i3.Future<_i5.Success>? editUser(_i4.UserModel? user) =>
      (super.noSuchMethod(Invocation.method(#editUser, [user]))
          as _i3.Future<_i5.Success>?);
}
